name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-todo-api:

    runs-on: ubuntu-latest
    working-directory: ./todo_api

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose
    - name: Clippy
      run: cargo clippy -- --deny clippy::all
  build-todo-web:

    runs-on: ubuntu-latest
    working-directory: ./todo_web

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose
    - name: Clippy
      run: cargo clippy -- --deny clippy::all
